name: Send Routine Push Notifications

on:
  schedule:
    # 매분마다 실행 (UTC 기준)
    - cron: '* * * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send routine notifications
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/send-routine-notifications" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}' 